version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - yum install -y nginx

  pre_build:
    commands:
      - echo "Setting permissions"
      - chmod +x infra-monitor.sh

 build:
  commands:
    - chmod +x infra-monitor.sh
    - ./infra-monitor.sh || true

post_build:
  commands:
    - echo "Validating logs"

    - |
      if [ -f infra_monitor.log ]; then
        grep "ERROR" infra_monitor.log && {
          echo "Build failed"
          exit 1
        } || echo "No errors found"
      else
        echo "Log file not found, skipping validation"
      fi
